//! `sanctum config` — View or edit configuration.

use std::fs;
use std::path::PathBuf;

use sanctum_types::errors::CliError;

/// Run the config command.
pub fn run(edit: bool, recommended: bool) -> Result<(), CliError> {
    if recommended {
        #[allow(clippy::print_stdout)]
        {
            print!("{}", recommended_config());
        }
        return Ok(());
    }

    let config_path = find_config_path();

    if edit {
        let editor = std::env::var("EDITOR")
            .or_else(|_| std::env::var("VISUAL"))
            .unwrap_or_else(|_| "vi".to_string());

        let path = if let Some(p) = config_path { p } else {
            // Create default config in standard location
            let paths = sanctum_types::paths::WellKnownPaths::default();
            let config_file = paths.config_dir.join("config.toml");
            fs::create_dir_all(&paths.config_dir)?;

            if !config_file.exists() {
                fs::write(&config_file, default_config())?;
            }
            config_file
        };

        #[allow(clippy::print_stdout)]
        {
            println!("Opening {} in {editor}...", path.display());
        }

        let status = std::process::Command::new(&editor)
            .arg(&path)
            .status()
            .map_err(|e| CliError::InvalidArgs(format!("failed to open editor '{editor}': {e}")))?;

        if !status.success() {
            return Err(CliError::InvalidArgs("editor exited with error".to_string()));
        }
    } else {
        match config_path {
            Some(path) => {
                let content = fs::read_to_string(&path)?;
                #[allow(clippy::print_stdout)]
                {
                    println!("Configuration: {}", path.display());
                    println!("{:-<72}", "");
                    println!("{content}");
                }
            }
            None => {
                #[allow(clippy::print_stdout)]
                {
                    println!("No configuration file found.");
                    println!();
                    println!("Run `sanctum init` to create one, or `sanctum config --edit` to create and edit.");
                    println!();
                    println!("Current defaults:");
                    println!("{:-<72}", "");
                    println!("{}", default_config());
                }
            }
        }
    }

    Ok(())
}

fn find_config_path() -> Option<PathBuf> {
    let local = PathBuf::from(".sanctum/config.toml");
    if local.exists() {
        return Some(local);
    }

    let paths = sanctum_types::paths::WellKnownPaths::default();
    let global = paths.config_dir.join("config.toml");
    if global.exists() {
        return Some(global);
    }

    None
}

const fn default_config() -> &'static str {
    r#"# Sanctum configuration
# https://sanctum.dev/docs/config

[sentinel]
watch_pth = true
watch_credentials = true
watch_network = false
pth_response = "quarantine"

[ai_firewall]
redact_credentials = true
claude_hooks = true
mcp_audit = true

[budgets]
# default_session = "$50"
# default_daily = "$200"
alert_at_percent = 75
"#
}

const fn recommended_config() -> &'static str {
    r#"# Sanctum recommended configuration
# Generated by: sanctum config --recommended
# Review and customise for your environment.

[sentinel]
watch_pth = true
watch_credentials = true
watch_network = true
pth_response = "quarantine"

[sentinel.network]
poll_interval_secs = 30
learning_period_days = 7
transfer_threshold_bytes = 104857600  # 100 MB

[ai_firewall]
redact_credentials = true
claude_hooks = true
mcp_audit = true

[[ai_firewall.mcp_rules]]
tool = "filesystem_write"
restricted_paths = ["/etc/*", "/usr/*", "/System/*", "~/.ssh/*", "~/.aws/*"]

[[ai_firewall.mcp_rules]]
tool = "filesystem_read"
restricted_paths = ["~/.ssh/id_*", "~/.aws/credentials"]

[budgets]
default_session = "$50"
default_daily = "$200"
alert_at_percent = 75

[budgets.providers.openai]
session = "$30"
daily = "$100"
allowed_models = ["gpt-4o", "gpt-4o-mini", "o3-mini"]

[budgets.providers.anthropic]
session = "$30"
daily = "$100"
allowed_models = ["claude-sonnet-4-6", "claude-haiku-4-5"]

[budgets.providers.google]
session = "$20"
daily = "$80"
allowed_models = ["gemini-2.5-pro", "gemini-2.5-flash"]
"#
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn recommended_config_parses_as_valid_toml() {
        let result = toml::from_str::<sanctum_types::config::SanctumConfig>(recommended_config());
        assert!(result.is_ok(), "recommended config should parse as valid TOML: {:?}", result.err());
    }
}
