//! `sanctum config` — View or edit configuration.

use std::fs;
use std::io::Write;
use std::path::PathBuf;

use sanctum_types::errors::CliError;

/// Run the config command.
pub fn run(edit: bool, recommended: bool) -> Result<(), CliError> {
    if recommended {
        #[allow(clippy::print_stdout)]
        {
            print!("{}", recommended_config());
        }
        return Ok(());
    }

    let config_path = find_config_path();

    if edit {
        let editor = std::env::var("EDITOR")
            .or_else(|_| std::env::var("VISUAL"))
            .unwrap_or_else(|_| {
                #[allow(clippy::print_stderr)]
                {
                    eprintln!("Opening in vi (set $EDITOR to change)...");
                }
                "vi".to_string()
            });

        let path = if let Some(p) = config_path {
            p
        } else {
            // Create default config in standard location
            let paths = sanctum_types::paths::WellKnownPaths::default();
            let config_file = paths.config_dir.join("config.toml");
            // Ensure parent directories exist, then create the config
            // directory with restricted (0o700) permissions.
            if let Some(parent) = paths.config_dir.parent() {
                fs::create_dir_all(parent)?;
            }
            sanctum_types::fs_safety::ensure_secure_dir(&paths.config_dir)?;

            if !config_file.exists() {
                // Atomic write: write to temp file with secure permissions, sync,
                // then rename into place.
                let tmp_path = config_file.with_extension("tmp");
                {
                    let mut file = fs::File::create(&tmp_path)?;
                    sanctum_types::fs_safety::fchmod_600(&file)?;
                    file.write_all(default_config().as_bytes())?;
                    file.sync_all()?;
                }
                fs::rename(&tmp_path, &config_file)?;
            }
            config_file
        };

        #[allow(clippy::print_stdout)]
        {
            println!("Opening {} in {editor}...", path.display());
        }

        let status = std::process::Command::new(&editor)
            .arg(&path)
            .status()
            .map_err(|e| {
                CliError::CommandFailed(format!("failed to open editor '{editor}': {e}"))
            })?;

        if !status.success() {
            return Err(CliError::CommandFailed(
                "editor exited with error".to_string(),
            ));
        }
    } else {
        match config_path {
            Some(path) => {
                let content = fs::read_to_string(&path)?;
                #[allow(clippy::print_stdout)]
                {
                    println!("Configuration: {}", path.display());
                    println!("{:-<72}", "");
                    println!("{content}");
                }
            }
            None => {
                #[allow(clippy::print_stdout)]
                {
                    println!("No configuration file found.");
                    println!();
                    println!("Run `sanctum init` to create one, or `sanctum config --edit` to create and edit.");
                    println!();
                    println!("Current defaults:");
                    println!("{:-<72}", "");
                    println!("{}", default_config());
                }
            }
        }
    }

    Ok(())
}

fn find_config_path() -> Option<PathBuf> {
    let local = PathBuf::from(".sanctum/config.toml");
    if local.exists() {
        return Some(local);
    }

    let paths = sanctum_types::paths::WellKnownPaths::default();
    let global = paths.config_dir.join("config.toml");
    if global.exists() {
        return Some(global);
    }

    None
}

const fn default_config() -> &'static str {
    r#"# Sanctum configuration
# https://github.com/postrv/sanctum-oss/blob/main/docs/ARCHITECTURE.md

[sentinel]
watch_pth = true
watch_credentials = true
watch_network = false
pth_response = "quarantine"

[ai_firewall]
redact_credentials = true
claude_hooks = true
mcp_audit = true

[budgets]
# default_session = "$50"
# default_daily = "$200"
alert_at_percent = 75
"#
}

const fn recommended_config() -> &'static str {
    r#"# Sanctum recommended configuration
# Generated by: sanctum config --recommended
# Review and customise for your environment.

[sentinel]
watch_pth = true
watch_credentials = true
watch_network = true
pth_response = "quarantine"

[sentinel.network]
poll_interval_secs = 30
exfiltration_warn_bytes = 5242880       # 5 MB
exfiltration_block_bytes = 20971520     # 20 MB
exfiltration_window_secs = 60
exfiltration_host_allowlist = []

# [sentinel.go]
# allowlist = ["github.com/my-org/internal-module"]
# Note: setting trusted_prefixes REPLACES the defaults; include the built-ins you want to keep.
# trusted_prefixes = ["golang.org/x/", "google.golang.org/", "cloud.google.com/go/", "github.com/golang/", "github.com/my-org/"]

# [sentinel.cargo]
# allowlist = ["my-internal-crate"]
# warn_build_scripts = true              # warn when cargo downloads new crates (build.rs risk)

# [sentinel.pip]
# allowlist = ["numpy", "pandas"]
# warn_source_installs = true            # warn about setup.py execution risk
# require_binary_only = false            # set true to block pip install without --only-binary :all:

[ai_firewall]
redact_credentials = true
claude_hooks = true
mcp_audit = true
check_package_existence = true
package_check_timeout_ms = 5000          # 5s default; increase for slow networks

[[ai_firewall.mcp_rules]]
tool = "filesystem_write"
restricted_paths = ["/etc/*", "/usr/*", "/System/*", "~/.ssh/*", "~/.aws/*"]

[[ai_firewall.mcp_rules]]
tool = "filesystem_read"
restricted_paths = ["~/.ssh/id_*", "~/.aws/credentials"]

# CEL expression rules for advanced MCP policy logic.
# Evaluated after glob rules. Available variables:
#   tool_name (string), paths (list of strings), payload_size (int)
# Action: "deny" (default), "allow", or "warn"

# Example: Block write_file for files larger than 100KB
# [[ai_firewall.mcp_cel_rules]]
# expression = 'tool_name == "write_file" && payload_size > 102400'
# action = "deny"

# Example: Warn on any database tool usage
# [[ai_firewall.mcp_cel_rules]]
# expression = 'tool_name.startsWith("database_")'
# action = "warn"

[ai_firewall.docker]
# Note: setting trusted_registries REPLACES the defaults; include the built-ins you want to keep.
trusted_registries = ["docker.io", "ghcr.io", "gcr.io", "public.ecr.aws", "registry.k8s.io"]
warn_latest = true                       # warn on :latest or untagged images
warn_remote_add = true                   # warn on ADD with remote URLs in Dockerfiles
warn_pipe_install = true                 # warn on curl|sh patterns in Dockerfile RUN

[budgets]
default_session = "$50"
default_daily = "$200"
alert_at_percent = 75

# Anthropic: claude-opus-4-6 ($15/$75), claude-sonnet-4-6 ($3/$15), claude-haiku-4-5 ($1/$5)
[budgets.providers.anthropic]
session = "$30"
daily = "$100"
allowed_models = ["claude-opus-4-6", "claude-sonnet-4-6", "claude-haiku-4-5"]

# OpenAI: gpt-5.4 ($2.50/$10), gpt-5.4-mini ($0.40/$1.60), gpt-5.4-nano ($0.10/$0.40)
[budgets.providers.openai]
session = "$30"
daily = "$100"
allowed_models = ["gpt-5.4", "gpt-5.4-mini", "gpt-5.4-nano"]

# Google: gemini-3.1-pro ($1.25/$5), gemini-3-flash ($0.15/$0.60), gemini-2.5-flash ($0.15/$0.60)
[budgets.providers.google]
session = "$20"
daily = "$80"
allowed_models = ["gemini-3.1-pro", "gemini-3-flash", "gemini-2.5-flash"]

# xAI: grok-4.20-0309-reasoning ($3/$15), grok-4-1-fast-reasoning ($1/$5)
[budgets.providers.xai]
session = "$20"
daily = "$80"
allowed_models = ["grok-4.20-0309-reasoning", "grok-4-1-fast-reasoning"]
"#
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn recommended_config_parses_as_valid_toml() {
        let result = toml::from_str::<sanctum_types::config::SanctumConfig>(recommended_config());
        assert!(
            result.is_ok(),
            "recommended config should parse as valid TOML: {:?}",
            result.err()
        );
    }
}
